### ISSUE TITLE
Integration test alt_home fails: net-ssh requires Ruby version >= 2.0

### ISSUE THREAD

**Issue by dhoer** [dhoer/chef-java_se#11]
This occurs on Windows during integration testing with test-kitchen.

Full stack trace:

```
-----> Setting up Busser
       Creating BUSSER_ROOT in C:\Users\vagrant\AppData\Local\Temp\verifier
       Creating busser binstub
       Installing Busser plugins: busser-serverspec
       Plugin serverspec installed (version 0.5.7)
-----> Running postinstall for serverspec plugin
       Suite path directory C:/Users/vagrant/AppData/Local/Temp/verifier/suites does not exist, skipping.
       Transferring files to <alt-home-windows-2012r2>
-----> Running serverspec test suite
-----> Installing Serverspec..
$$$$$$ C:/opscode/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:533:in `ensure_required_ruby_version_met': net-ssh requires Ruby version >= 2.0. (Gem::InstallError)
$$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:747:in `pre_install_checks'
$$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:208:in `install'
$$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/request_set.rb:97:in `block in install'
$$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/request_set.rb:84:in `each'
$$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/request_set.rb:84:in `install'
$$$$$$ 	from C:/opscode/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:371:in `install'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/busser-0.7.1/lib/busser/rubygems.rb:44:in `install_gem'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/busser-0.7.1/lib/busser/helpers.rb:57:in `install_gem'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/busser-serverspec-0.5.7/lib/busser/runner_plugin/serverspec.rb:60:in `install_serverspec'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/busser-serverspec-0.5.7/lib/busser/runner_plugin/serverspec.rb:33:in `test'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `block in invoke_all'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `each'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `map'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `invoke_all'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/group.rb:232:in `dispatch'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:115:in `invoke'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/busser-0.7.1/lib/busser/command/test.rb:43:in `block in perform'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/busser-0.7.1/lib/busser/command/test.rb:35:in `each'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/busser-0.7.1/lib/busser/command/test.rb:35:in `perform'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `block in invoke_all'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `each'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `map'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `invoke_all'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/group.rb:232:in `dispatch'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:115:in `invoke'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:40:in `block in register'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:359:in `dispatch'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/thor-0.19.0/lib/thor/base.rb:440:in `start'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/busser-0.7.1/bin/busser:8:in `<top (required)>'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/bin/busser:23:in `load'
$$$$$$ 	from C:/Users/vagrant/AppData/Local/Temp/verifier/gems/bin/busser:23:in `<main>'
>>>>>> Verify failed on instance <alt-home-windows-2012r2>.
```

**Comment by dhoer** [comment]
Add Gemfile with net-ssh pessimistically locked to 2.x.
