### ISSUE TITLE
Gem install of open_uri_redirections can fail on Window

### ISSUE THREAD

**Issue by dhoer** [dhoer/chef-java_se#19]
Gem install of open_uri_redirections can cause: 
- [FATAL] failed to allocate memory
- or [BUG] w32_resume_thread: The handle is invalid.

Check that `MaxMemoryPerShellMB` for chef-client is set for older Windows Machines. 	

The chef-client and Ohai typically require more memory than the default setting allows. Increase this value to 300MB. Only required on Windows Server 2008 R2 Standard and older. The default in Windows Server 2012 was increased to 1024MB.

Making open_uri_redirections a monkey patch in the future might avoid this issue.

**Comment by dhoer** [comment]
================================================================================
    Error executing action `install` on resource 'chef_gem[allow for https to http redirections]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '-1073741571'
    ---- Begin output of C:/opscode/chef/embedded/bin/gem install open_uri_redirections -q --no-rdoc --no-ri -v "0.2.1" ----
    STDOUT:
    STDERR: <main>: [BUG] w32_resume_thread: The handle is invalid.
    
    ruby 2.1.8p440 (2015-12-16 revision 53160) [x64-mingw32]
    
    -- Control frame information -----------------------------------------------
    c:0001 p:0000 s:0002 E:001048 TOP    [FINISH]
    
    
    -- C level backtrace information -------------------------------------------
    
    -- Other runtime information -----------------------------------------------
    ---- End output of C:/opscode/chef/embedded/bin/gem install open_uri_redirections -q --no-rdoc --no-ri -v "0.2.1" ----
    Ran C:/opscode/chef/embedded/bin/gem install open_uri_redirections -q --no-rdoc --no-ri -v "0.2.1" returned -1073741571

    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/java_se/recipes/_download_java.rb
    
     38:   chef_gem 'allow for https to http redirections' do
     39:     package_name 'open_uri_redirections'
     40:     version '0.2.1'
     41:     compile_time false if Chef::Resource::ChefGem.method_defined?(:compile_time)
     42:   end
     43:
    
    Compiled Resource:
    ------------------
    # Declared in C:/chef/cache/cookbooks/java_se/recipes/_download_java.rb:38:in `from_file'
    
    chef_gem("allow for https to http redirections") do
      package_name "open_uri_redirections"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :chef_gem
      cookbook_name "java_se"
      recipe_name "_download_java"
      version "0.2.1"
      gem_binary "C:/opscode/chef/embedded/bin/gem"
    end
    
    Platform:
    ---------
    x64-mingw32

**Comment by dhoer** [comment]
[FATAL] failed to allocate memory

    ================================================================================
    Error executing action `install` on resource 'chef_gem[allow for https to http redirections]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of C:/opscode/chef/embedded/bin/gem install open_uri_redirections -q --no-rdoc --no-ri -v "0.2.1" ----
    STDOUT:
    STDERR: [FATAL] failed to allocate memory
    ---- End output of C:/opscode/chef/embedded/bin/gem install open_uri_redirections -q --no-rdoc --no-ri -v "0.2.1" ----
    Ran C:/opscode/chef/embedded/bin/gem install open_uri_redirections -q --no-rdoc --no-ri -v "0.2.1" returned 1

    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/java_se/recipes/_download_java.rb
    
     38:   chef_gem 'allow for https to http redirections' do
     39:     package_name 'open_uri_redirections'
     40:     version '0.2.1'
     41:     compile_time false if Chef::Resource::ChefGem.method_defined?(:compile_time)
     42:   end
     43:
    
    Compiled Resource:
    ------------------
    # Declared in C:/chef/cache/cookbooks/java_se/recipes/_download_java.rb:38:in `from_file'
    
    chef_gem("allow for https to http redirections") do
      package_name "open_uri_redirections"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :chef_gem
      cookbook_name "java_se"
      recipe_name "_download_java"
      version "0.2.1"
      gem_binary "C:/opscode/chef/embedded/bin/gem"
    end
    
    Platform:
    ---------
    x64-mingw32
